const lists = {
  names: [
    "Wet William",
    "Blaster Keaton",
    "Butch Sunbeams",
    "Billions Thaumaturgy",
    "Sylvan Seawater",
    "Sisyphus Saturnine",
    "Wilimander Plause",
    "Peace Finally",
    "Pillbug Balboa",
    "Steve Countersteve",
    "Margot Bookbinder Milkman",
    "Calamitous Nightmother",
    "Halstane Flek",
    "Whitney Dustgate",
    "Thiccums Juggalette",
    "Garbanzo Dean",
    "Quadriceps Godzilla",
    "Yottachad Cranewife",
    "Geodesic Dave",
    "Robert Yaga",
    "Anti-Todd",
    "Immolation Sphere",
    "Shepherd's Silloutte",
    "Wrecker Philadelphia",
    "Twelve Thousand Dollars",
    "California Time Dilation",
    "Navy Railgun",
    "Lawrence Marrowthief",
    "Lexicographica Milktooth",
    "Harcourt Horsewater",
    "Omenifus Soup",
    "Alabaster Weavesnatch",
    "Ichabod Pelican",
    "Cannonball Chidi",
    "Dilkus Redhook",
    "Terwilliger \"Youtube\" Terwilliger",
    "Low Key The Baba Yaga",
    "Game Five",
    "Hope Springs Eternal",
    "Hotboxed Miata",
    "Marfideldus Plane",
    "New Rose Milk Hotel",
    "Dan Quayleman",
    "Laguna Todd",
    "Slain Hawthorne",
    "Hot Diggity",
    "Brutallion Dogthief",
    "Gilligan Roosevelt Troubadour Troutman",
    "Pidgeonmade Moon",
    "Hooligan Oof",
    "Wilmot Witchfinder",
    "Nosebleed Seats",
    "Milkworms Milkworms",
    "Honest Dirtprince",
    "Great Granite Spire",
    "Cousin Doomrider",
    "Perihelia Griefhaven",
    "Son Pyramid",
    "Lone Argonaut",
    "Regular-Sized Edward Cannon",
    "Boo Gamecube",
    "Pegg Legg",
    "Reverend Hooligan",
    "Booker T. V.",
    "Slim Harmonics",
    "Graviton Bomb Delloitte",
    "Harmonica Blackpine",
    "Sweat Equity",
    "Paris-By-Way-Of-Detroit",
    "Cassiopeia Halifax",
    "Andromedes Fiveiron",
    "Haunted Summer",
    "Drunks Baldwin",
    "Broccoli Pubchatter",
    "Ganymede Processional",
    "Dule Tunguska",
    "Obstinacy of the Dispossessed",
    "Mortal Axis",
    "Orbital Dunkleader",
    "Ten Years Buried",
    "Judas Dafodillionare",
    "Raekwon Quake",
    "Polyhed'Ron Whelm",
    "Eigen-Victor Loop",
    "Horatio Beefweapon",
    "Hypatia Sunstruck",
    "Allegory of the Moon-Posessed",
    "Olifant Crocodil",
    "Harmonious Chordata",
    "Irascible Tom",
    "Oliver Notionsbane",
    "Saxophone Nightmare II",
    "Nightingale Switchblade-Pettigrew",
    "Jupiter Swordlogic",
    "Wormweather Tapestry",
    "Biblical Omaha",
    "Seance Swanvigil",
    "Wasp-Eater Oligarch",
    "Never Dare Hope",
    "Godforsaken Lizard",
    "Obelisk Ikegami",
    "Toledo Octagon",
    "Ransommelier Dunkirk",
    "Branson Bouchard",
    "Ommegang Proboscuttio",
    "Antigone Owlfather",
    "Nope Hogan",
    "Fatima Duckworth",
    "Olivander Timecop",
    "Dawn Dialectics",
    "Pygmalionite Oak",
    "Dilligan Golfclap",
    "Philomena Mooncop",
    "Telomere Applegate",
    "Tallahassee Hallelujah",
    "Dawnwrought Yeet",
    "Mahogany Thoughtcrime",
    "Orpheus Sleep",
    "Delver Goonboggle",
    "Dogs: Ohayo",
    "Autumn Toothkeeper",
    "Plausible Maud",
    "Ampersands Often",
    "Guxue Lightrider",
    "Peoria Burgergun",
    "Big Yikes",
    "Jikes Runewelder",
    "Mood Enough",
    "Thwartlance Bloodrot",
    "Reverse Tracheotomy Tuesday",
    "Dichotomous Wife-Energy",
    "Gourdhampton Tubewallop",
    "Incontrovertible Kill-Field",
    "Relative Designator",
    "Irreversible Flex",
    "Cherenkov Stutterglow",
    "E.M. Skipglider",
    "\"Unsinkable\" Radio Esposito",
    "Reversible Junebug",
    "Proprietous Oscar",
    "Entropic Tidecatcher",
    "Doubledoug Meerkat",
    "Daring Scopecrawler",
    "Maximum Horkheimer",
    "Median Headroom",
    "Looper Wave-Motion",
    "Distant Action",
    "Radar Skipjacker",
    "Liliput Erstwhile",
    "Mothra Doubledown",
    "Minsk Occultant",
    "Doomed Rhymeweaver",
    "Marine Okemba",
    "Subtextual Emile",
    "Bathos Pathos",
    "Baphometa Rashid",
    "Small Emperor Moth",
    "Saturnalia Inkwell",
    "Pavel Timeheist",
    "Lepidoptera Poppycock",
    "Motheaten Dynasty",
    "Echopraxia Wallander",
    "Lattitude of Aplasia",
    "Leopold Imbroglio",
    "Fam Nightmissile",
    "Smoke Toastwhip",
    "Micron Gunn",
    "Pitbull Saebyolbe",
    "Mox Atriedes",
    "Mossdrenched, Forgotten",
    "Illith Truncheon",
    "Beast Moog",
    "Lesbian Moonbase",
    "Tyranica Walters",
    "Memory Gospel",
    "Anne Allegory",
    "A Problem",
    "Wise but Malfeasant Ghost",
    "Phantom Tim Syndrome",
    "Hell-For-Leather Protocol",
    "Adult Headlong",
    "Disquiet Elizabeth",
    "Winter's Discontent",
    "Eternal Shortsweather",
    "Sophia, Our Lady of Perpetual Motion",
    "Cool and Laborious Paul",
    "Indefatigable Honeymap",
    "Meticulous Grace",
    "Contiguous Emma",
    "Tangible Tyler",
    "Indeterminacy of Translation",
    "Inscrutability of Reference",
    "Avery Undisproven",
    "Catherine Bloodritual Wellingsley III",
    "The Boat From \"Jaws\"",
    "Judge Aristophanes",
    "Cool Official",
    "Careful Discourse",
    "Football Miette",
    "Intelligible Penelope",
    "Adidas Funk",
    "K.O. Brooklyn",
    "Island of Esther",
    "Iris Ultra-Light",
    "Madeline Twice-Arisen",
    "Hadley Hopeless",
    "Giant Enemy Crab",
    "Horse Cop II",
    "Arbalest Peninsula",
    "Arigato Kickflip",
    "5 Arkwright Cutpurse",
    "Devilish Admiral \"Feet Pix\" Matsumoto",
    "Churlish Dirge",
    "Madeline Sunglasses",
    "3D Todd",
    "Teagan Hornsabbath",
    "Violence Divine",
    "Laila Chesscaptain",
    "Mastodon's Discount",
    "Tony Hawk",
    "Eloise Tortuga",
    "Leg Dei",
    "Foghorn Context",
    "Strongsister Nightvision",
    "Ivory Tomb",
    "Cyclical History X",
    "Sylvester Vestsilver Test-Svelter Toad",
    "Talcum Wombfeather",
    "Litigious Aurora",
    "Calliope Coolhand",
    "Yakety Onassis",
    "Tiberia Slowjam",
    "Jung Pope",
    "Long-Forgotten Hank Montgomery",
    "Applesauce! :)",
    "Whip Ghostrider",
    "Judgemental Pete",
    "Ol' Whispy Bootlick",
    "Spidercoveted Narcissa",
    "cavitation.sonoluminescence.info",
    "Hank Williams MMXIX",
    "Y Iotta",
    "Sparks Tubeshark",
    "Calculator Minestrone",
    "Workahol Godswilling",
    "Oval Valentine",
    "Cold Keith",
    "Tit Whimsy",
    "Bloodhound Tatsuya",
    "Wildfire Township",
    "DVS Varietal",
    "Pizza Tuxedo",
    "None Wolfgrinder",
    "Earth Doubleprime",
    "Leftbeef Odinsdottir",
    "Godswill Song",
    "Ode Signifier",
    "Kim Süsser Tod",
    "Algebra Knifemuseum",
    "Guts Isomorph",
    "T.U.G.B.O.A.T.",
    "Just Alice 👍",
    "Orcus \"Unicode Consortium\" Gillchrest",
    "Basic Multilingual Plane",
    "Inverted Olivia",
    "Fallible Macintosh",
    "Cascade Pasadena",
    "Theophant Alcatraz",
    "Poncho Capone",
    "Applebaum Jeanist",
    "Strafe Ontario",
    "Quicksand Monitor",
    "Gus Van Cargo",
    "Velvetine Tangent",
    "Halifax Delany",
    "Ligature Antiquity",
    "Winsome Pasquale",
    "Sanguine Turbinado",
    "Google Albatross",
    "Bennigan's Capricorn",
    "Celementine's Particulate",
    "Overhead Pressure",
    "Whiskey Francisco",
    "Faberge Alphonse",
    "Hardwater Adjacent",
    "Alistair Half-acre",
    "Pogo Carcinogen",
    "Nolan Probably",
    "Cantilever Grey",
    "Significance Bloom",
    "Tip Footman",
    "Borealis Provost",
    "Ol' Dirty Parthenon",
    "Raphael Damagedone",
    "Blush Gravitas",
    "Waltham Eglantine",
    "Kip Oscillante",
    "Tertiary Children",
    "Gentle Calderon",
    "Heat Copkill",
    "Juice Trashfire",
    "Twiceduke Splines",
    "CatVatican Reticulant",
    "Antarctican Thawed",
    "Peristalsis Cronenberg",
    "Scam Likely",
    "Hoagie Omakase",
    "Perfect Shotgun Heartbreak",
    "Garnacle Booze",
    "JPEG Van Helsing",
    "You, the reader",
    "The Girl Reading This",
    "Harmonic Mario",
    "Yucatan Sam",
    "Biggie Krautrock",
    "Maersk Blue",
    "Nephew Deepstorage",
    "Daffy Kong",
    "Gilbert Godfreer",
    "Miyazaki Moomintank",
    "Manitoba Tuscaloosa",
    "Loosey Vibejacker",
    "He-done-it-again Williamsburg",
    "Pisschrist Controversy",
    "Lubey Nickels",
    "Ratthew Leonard",
    "Waluwaldo",
    "Danthony Rambo",
    "Boobie Druthers",
    "Ramiel MacDaniel",
    "Mobile New Century (After War) Malcolm X",
    "Thorin Goofsbane",
    "Grizzly Sunrise",
    "Meef Bilk",
    "Frutiger Aero",
    "Tank War Europa",
    "Philanthropus Wethusband",
    "Cobalt Riptide",
    "Josh the Stampede",
    "Linear Tidekiller",
    "Society Watkins",
    "Brian Who-you-met-at-that-party",
    "Becca from Tinder",
    "Media Literacy",
    "Sudden Rainstorm",
    "Mouthapple Portugese",
    "Hercules Troubadourius"
  ],

  stats: [
    "Strength",
    "Wisdom",
    "Intelligence",
    "Charisma",
    "Dexterity",
    "Constitution",
    "Stamina",
    "Chirality",
    "Constitutionality",
    "Mass",
    "IQ",
    "Muscles",
    "EQ",
    "Dogs",
    "Vertical Leap",
    "Toes",
    "Police Evasion Modifier",
    "Gravitas",
    "Points",
    "Gold",
    "Friends",
    "Remaining Lives",
    "Bone Density",
    "Recalcitrance",
    "Gender",
    "Shoe Size",
    "Average Speed",
    "Mice",
    "Talent",
    "Attentiveness",
    "Bell Peppers",
    "Humility",
    "Credit Score",
    "Bones",
    "Birth Weight",
    "Surplus Value",
    "Teeth",
    "Flux Capacity",
    "Cool",
    "Edge",
    "pH",
    "Length",
    "Kills",
    "Drag Coefficient",
    "Vibes",
    "Guns",
    "Knives",
    "Swords",
    "Bats",
    "Crime",
    "Justice",
    "Time",
    "DPS",
    "Tables",
    "Pulchritude",
    "Power",
    "Strength (inner)",
    "Opulence",
    "Luck",
    "Dad Energy",
    "Thickness",
    "Decisiveness",
    "Jest",
    "Questions",
    "Defense",
    "Legs",
    "War",
    "Miscellaneous",
    "Rank",
    "Moms",
    "Eyes",
    "Experiences",
    "Dreams",
    "Modesty",
    "Guilt",
    "Boats Destroyed",
    "Audacity",
    "Cumulative Upkeep",
    "Memorability",
    "Cardinality",
    "Problems",
    "Hobbies",
    "Carbon Footprint",
    "Submersibility",
    "Baggage",
    "Sportsmanship",
    "Hot Dogsmanship",
    "Plenitude",
    "Archery",
    "Pronouns",
    "Backstory", 
    "Communism"
  ],

  jobs: [
    "Cherub",
    "Cyberdemon",
    "Milk Architect",
    "Heckler",
    "Herald",
    "Harbinger",
    "Giant Fluffy Dog",
    "Actual Worm",
    "None",
    "Unclear",
    "???",
    "Castabout",
    "Child",
    "God",
    "Agitator",
    "Lecturer",
    "Bodybuilder",
    "Refuses to Say",
    "Elf",
    "Warrior",
    "Pope",
    "Anti-Pope",
    "Minor Demon",
    "Demolitionist",
    "Reverse Demolitionist",
    "Gardener",
    "Villager",
    "Tinker",
    "Tailor",
    "Soldier",
    "Spy",
    "Sailor",
    "Sailor Scout",
    "Ex-Mime",
    "Travel Agent",
    "Slime",
    "Dungeoneer",
    "Hacker",
    "Pop Idol",
    "Smuggler",
    "Bounty Hunter",
    "Idealist",
    "Tree Whisperer",
    "Ghost Hunter (licensed)",
    "Iconoclast",
    "Dream Weaver",
    "Art Critic",
    "Entropy Reverser",
    "Mean Bird",
    "Traitor",
    "Geometer",
    "Witch",
    "Crab Singer",
    "Dancer",
    "Devil's Advocate",
    "Tycoon",
    "Celebrity Chef",
    "Dracula",
    "Blues Musician",
    "Bard",
    "Professional Gamer",
    "Journalist",
    "Teaching Assistant",
    "Fetish Model",
    "Political Prisoner",
    "Anarchist",
    "Toady",
    "Goon",
    "Monarch",
    "Midwife",
    "Actuary",
    "Alderman",
    "Mayor",
    "Ale-Wife",
    "Balloonist",
    "Beekeeper",
    "Apprentice",
    "Artificer",
    "Pit Brow Lass",
    "Gangleader",
    "Barkeep",
    "Gondolier",
    "Batperson",
    "Bird Catcher",
    "Bloodletter",
    "Pundit",
    "Bonesetter",
    "Top",
    "Punisher",
    "Carnifex",
    "Wheelwright",
    "Professional Wrestler",
    "Amateur Wrestler",
    "Chimney Sweep",
    "Data Sanitizer",
    "Cinder Wench",
    "Chronologist",
    "Decoy",
    "Dragoon",
    "Drifter",
    "Elephant Dentist",
    "Exorcist",
    "Wedding Planner",
    "Prophet (false)",
    "Haberdasher",
    "Lighthouse Operator",
    "Delinquent",
    "Horse Knave",
    "Magician",
    "Mangler",
    "Mudlark",
    "Nightwalker",
    "Notarist",
    "Pattern Maker",
    "Piper",
    "Printer's Devil",
    "Publican",
    "Rubbernecker",
    "Shambler",
    "Steeplejack",
    "Sword Collector",
    "Pig Destroyer",
    "Wet Nurse",
    "Lamplighter",
    "Theorist",
    "Projectionist",
    "Nomenclator",
    "Fashion Cop",
    "Psychic",
    "Propagandist",
    "Schoolmarm",
    "Attorney General",
    "Assassin",
    "Getaway Driver",
    "Drone Pilot",
    "Mysterious Athlete",
    "Doctoral Candidate",
    "Detective",
    "Private Investigator",
    "Public Investigator",
    "Unknown Assailant",
    "Cowboy Simulator",
    "Oracle",
    "Unmaker",
    "Reverse-Engineer (civil)",
    "Freelance Librarian",
    "Libertine",
    "Director of Social Engineering",
    "Freelance Cosmonaut",
    "Vice President",
    "Concrete Form Tube",
    "Mannequin",
    "Daredevil",
    "Stunt-Rocker",
    "Ghoul",
    "Poet Laureate",
    "Software Zoologist",
    "Wetware Developer",
    "Broodmother",
    "Ice Queen",
    "Gargoyle",
    "Typhoid Vector",
    "Cryptologist",
    "Prince (Wales)",
    "Deposed Sovereign",
    "Disgraced Artist",
    "Attitude Adjustment Specialist",
    "Cataclysm Adjudicant",
    "Pickpocket",
    "Cat Burglar",
    "Hamburglar",
    "Trapeze Scientist",
    "Jerk",
    "Witness",
    "Hexcleanser",
    "Flenser",
    "Animal",
    "Brickthrower",
    "Villain (general)",
    "Owl Impersonator",
    "Charlatan",
    "Mourner",
    "Dust Archivist",
    "Hoardsperson",
    "Obliviant",
    "Driftrider",
    "Tourist",
    "Barbarian",
    "Ball-Point Pen Thief",
    "Thought Leader",
    "Historical Revisionist",
    "Contortionist",
    "Rogue Chiropractor",
    "Forum Moderator",
    "Ringleader",
    "Circus Abolitionist",
    "Bug",
    "Henchperson",
    "Karate Champion",
    "Knife Instructor",
    "Holographic Dietician",
    "Illusory",
    "Eschatologist",
    "Goblin",
    "Unstable Boyfriend Prototype",
    "Bourgeois",
    "Petite bourgeois",
    "Proletariat",
    "Lumpenproletariat",
    "None to speak of",
    "Dry Nurse",
    "Blacksite notary"
  ],

  // moves: [
  //   "Monster Mash",
  //   "Regular Kick"
  // ],
  
  spells: [
    "Tragic Missile",
    "Death Touch",
    "Near-Death Touch",
    "Annoying Touch",
    "Astral Poke",
    "Create Salmon",
    "Dispel Salmon",
    "Speak with Jeff",
    "Reason With Insects",
    "Oops! All Centipedes",
    "Detect Magic Johnson",
    "Magic Fingers",
    "Cone of Awkwardness",
    "Contact Dad",
    "Beefening",
    "Protection from Wi-Fi",
    "Biteass",
    "Greased Lightning",
    "Mirthquake",
    "Detect Flirtation",
    "Dealer's Choice",
    "Greater Beefening",
    "Birthquake",
    "Chocolate Rain",
    "Detect Thoughtlessness",
    "Alter Pronouns",
    "Crown of Storms",
    "Hypernormalize",
    "Break Ice",
    "Zone of Cacophany",
    "Ray of Trademark Infrigement",
    "Bewilderment (Spell of the Year edition)"
  ],

  bonuses: [
    "fighting",
    "fishing",
    "role Playing",
    "charcuterie",
    "defense against the fine arts",
    "hacking",
    "martial arts (all kinds)",
    "breath (all kinds)",
    "executive function",
    "kissing",
    "dancing (salsa)",
    "dancing (dirty)",
    "freestyle rapping",
    "smalltalk",
    "big talk",
    "improv comedy",
    "first aid",
    "second aid",
    "narration",
    "fine arts",
    "sailing",
    "kayaking",
    "wrestling ",
    "karate",
    "judo",
    "cooking",
    "rhetoric",
    "fast talking",
    "massage",
    "knots (nautical)",
    "gardening",
    "telepathy",
    "gaming",
    "juggling",
    "juggling (contact)",
    "snake charming",
    "horse taming",
    "whistling",
    "jumping (long)",
    "arm wrestling",
    "tickle resistance",
    "swimming",
    "bird watching",
    "wiggling",
    "squirming",
    "computers",
    "poetry",
    "poetry (free verse)",
    "poetry (haiku)",
    "calligraphy",
    "vape tricks",
    "skateboarding",
    "roller blading",
    "jousting",
    "beekeeping",
    "astrology",
    "lore",
    "lore (unnecessary)",
    "beatboxing",
    "cake decoration",
    "breaking & entering",
    "larceny",
    "screenwriting",
    "knife skills",
    "biting",
    "violence",
    "sex (vanilla)",
    "sex (weird)",
    "arithmetic",
    "tax preparation",
    "yoga",
    "cold reading",
    "flirting",
    "photography",
    "lateral thinking",
    "gossip",
    "spanish",
    "gunfightistry",
    "basketball",
    "karaoke",
    "powerlifting",
    "running",
    "personal hygiene",
    "epidemiology",
    "improv dentistry",
    "chooglin'",
    "winging it",
    "skincare",
    "jokes",
    "hood rat shit",
    "etiquette",
    "jazz",
    "cultural sensitivity",
    "expectation management",
    "committing to the bit",
    "nintendo",
    "IP theft"
  ],

  items: [
    "Nunchucks",
    "Throwing stars",
    "Throwing darts",
    "Sword",
    "Sword (cursed)",
    "Katana (real)",
    "Katana (mall)",
    "Great sword",
    "Hammer (oversized, comedic)",
    "Gun",
    "Hammer",
    "Hammer (ball peen)",
    "Knife",
    "Gavel",
    "Stick",
    "Stick (big)",
    "Boomerang",
    "Rocks (normal)",
    "Rocks (cool)",
    "Guitar",
    "Guitar (acoustic)",
    "Guitarrón mexicano",
    "War tuba",
    "Tuba",
    "Saxophone",
    "Saxophone (weaponized)",
    "Clarinet",
    "Bassoon",
    "Flute",
    "Magic flute",
    "Magic flute (cursed)",
    "Combat flute",
    "Nuclear football",
    "Grenade",
    "Helicopter",
    "Mean bird",
    "Jar full of bees",
    "Wine bottle",
    "Toyota Camry",
    "Dog (unfriendly)",
    "Trained snake",
    // monkey island money joke
    // andor money joke
    "Wallet",
    "Chronoscepter",
    "Wand of shrinkage",
    "Wand of identification",
    "Wand of teleportation",
    "Wand of teleportation (cursed)",
    "Passport (real)",
    "Passport (fake)",
    "Parrot",
    "Several books",
    "Letter (sealed)",
    "Letter (handwritten)",
    "Whistle",
    "Playing cards",
    "Tome of the Ancients",
    "Religious pamphlets",
    "The void",
    "Immovable rod",
    "Blaster",
    "Shotgun shells",
    "Dagger",
    "Dagger (poisoned)",
    "Paperwork",
    "Several bees",
    "Pendant",
    "Bones",
    "Dice",
    "Dice (weighted)",
    "Dice (cursed)",
    "Lockpick",
    "Invisibility cloak",
    "Shoes",
    "Towel",
    "Towel (cursed)",
    "Boom-box",
    "Finger trap",
    "Finger trap (cursed)",
    "Car battery",
    "Sock full of batteries",
    "Condoms",
    "Canned lightning",
    "Empty jar",
    "Canteen",
    "Vial (inky substance)",
    "Vial (blood)",
    "Baked beans",
    "Fidget toy",
    "Camera",
    "Several candles",
    "Flashlight",
    "Megaphone",
    "Pills",
    "Briefcase (empty)",
    "Briefcase (filled with cash)",
    "Briefcase (filled with bugs)",
    "Loose change",
    "Loose bugs",
    "Roll of quarters",
    "Keychain",
    "Loose keys",
    "Another NPC",
    "Bag of holding",
    "A second inventory",
    "Business cards",
    "Large mirror",
    "Several eggs",
    "Tuning fork",
    "Driftwood",
    "Masquerade mask",
    "Clay figurines",
    "Blueprints",
    "Treasure map",
    "Energy drink",
    "Medkit",
    "Dumbbells",
    "Vape (cool mint)",
    "Weed",
    "Ketamine",
    "Flowers",
    "A single rose",
    "Cigarettes",
    "Cigarettes (cursed)",
    "Half smoked cigarette",
    "Flashbang",
    "Smoke bomb",
    "Trained dove",
    "Lunch",
    "Ring of power",
    "Ring of agility",
    "Ring of stealth",
    "Ring of mirth (cursed)",
    "Doctor's note",
    "Doctor's note (cursed)",
    "Pencil case",
    "Apple",
    "Jeff",
    "Bricks",
    "Candy",
    "Wedding ring",
    "Chalk",
    "Loose salt",
    "Various spices",
    "Binoculars",
    "Spyglass",
    "Compass",
    "Soup",
    "Dust",
    "Roll of tape",
    "Gasoline can",
    "Lighter",
    "Burner phone",
    "Sheet music",
    "Documents",
    "Documents (suspicious)",
    "Moths",
    "Motorcycle",
    "Karate manual",
    "Tapes",
    "Tapes (incriminating)",
    "Rubber chicken with a pulley in the middle",
    "Sundial",
    "Moondial",
    "Teeth",
    "Tools (miscellaneous)",
    "Screwdriver",
    "Wrench",
    "Rusty file",
    "Manilla folders",
    "Bell (mundane)",
    "Bell (mysterious)",
    "Loose sand",
    "Feathers",
    "Yarn",
    "Glue",
    "Lanyards",
    "Evidence (incriminating)",
    "Evidence (exonerating)",
    "Informative brochures",
    "Obelisk of boring futures"
  ],

  statuses: [
    "Normal",
    "Stunned",
    "Dazed",
    "Perforated",
    "Stoned",
    "Jacked up",
    "Locked in",
    "Logged off",
    "Tuned out",
    "Poisoned",
    "Alert",
    "Frightened",
    "Anxious",
    "Sad",
    "Depressed",
    "Tipsy",
    "Gone off that loud",
    "Thoughtful",
    "Respectful",
    "Confused",
    "Amused",
    "Pregnant",
    "Silent",
    "Alarmed",
    "Bleeding",
    "Stabbed",
    "Goofy",
    "Concerned",
    "Star-struck",
    "Angry",
    "Frostbitten",
    "Aflame",
    "Charred",
    "Roasted",
    "Warm",
    "Cold",
    "Silly",
    "Neutral",
    "Horny",
    "Jealous",
    "Relieved",
    "Busted",
    "Panicking",
    "Embarrassed",
    "Nude",
    "Bashful",
    "Secretive",
    "Wistful",
    "Thankful",
    "Blow'd up",
    "Wanted",
    "Unwanted",
    "Caught in 4k",
    "Trapped",
    "Escaping",
    "Hollerin'",
    "Away",
    "On PTO",
    "Done with this shit",
    "Ready",
    "Waiting",
    "Charmed",
    "Cross",
    "Inquisitive",
    "Hootin'",
    "Singing",
    "Listening",
    "Curious",
    "Dolled up",
    "Impressed",
    "Unimpressed",
    "Busy",
    "Available",
    "Injured",
    "Uninjured",
    "Cursed",
    "Cursing",
    "Shrinking",
    "Growing",
    "Hungry",
    "Sick",
    "Queasy",
    "Humming",
    "Vibrating",
    "Spinning",
    "Tired",
    "Sleepy",
    "Asleep",
    "Indolent",
    "Lazy",
    "Grumpy",
    "Pumped up",
    "Vibing",
    "Cute",
    "Kissy",
    "Wet",
    "It's complicated",
    "Unknown",
    "Unclear",
    "Just OK",
    "Fine",
    "Great",
    "Pretty good",
    "Alright",
    "Been better",
    "Worse for wear",
    "Humbled",
    "Beaten",
    "Battered",
    "Bruised",
    "Buggin' out",
    "Tweaking",
    "Dying",
    "Thriving",
    "Dancing",
    "Blasted",
    "Crossfaded",
    "Flavorblasted",
    "Mild cough",
    "Exploded",
    "Enlarged",
    "Satiated",
    "Normal",
    "Flexing",
    "Hangry",
    "Moonstruck",
    "Levitating",
    "Expansive",
    "Exhausted",
    "Stacked",
    "Superdeformed",
    "Smitten",
    "Enraged",
    "Swimming",
    "Skeptical",
    "Teething",
    "Berserking",
    "Clean",
    "Devastated",
    "Beset by devils",
    "Taken by the wind",
    "Ephemeral",
    "Intangible",
    "Tangible",
  ],

  affiliations: [
    "The Red Devil's Own Army of Laughing Bastards",
    "The Barony of Orphans",
    "The Crown of Storms",
    "Blackjackets",
    "Freemasons",
    "Boundmasons",
    "Wasp's Nest",
    "Lion's Den",
    "Sewerfolk",
    "Hill people",
    "Orcs, generally",
    "Fishfolk",
    "Central Intelligence",
    "Decentralized Intelligence",
    "Test Faction (Please Ignore)",
    "Rebel Alliance",
    "Ghouls",
    "Puglioni Family",
    "Pittsburg Steamrollers",
    "New Miami Freejackers",
    "Panther Moderns",
    "Thieves Guild",
    "Cutpurse Guild",
    "Local 358",
    "Steelworkers Union",
    "Glassblowers",
    "Black Hills Autonomous Zone",
    "Cyclopeans",
    "Ghostpunchers",
    "Knitting Club (terrorist group)",
    "Tree Party",
    "Snake Cultists",
    "Partitionists",
    "Cloudfolk",
    "Anonymous",
    "Unknown",
    "Radio Free Yrborgh",
    "Wastrels",
    "Horse Thieves",
    "Initiates of the Crimson Throne",
    "The Harlequins",
    "Agricultural Collective",
    "Eurasian Combine",
    "Heaven's Devils",
    "Mosquito Fleet",
    "Lost Battalion",
    "Ghost Brigade",
    "Dusk Chorus",
    "Cerberus Group",
    "Frost Shepherds",
    "Geometers",
    "Poetry Division",
    "The Silent Congress",
    "Rose Corps",
    "Torturers Guild",
    "Stonecutters Guild",
    "Second Communist Party of Yrborgh",
    "Fools Regiment",
    "Army of Light",
    "Orion Front",
    "The Red Women",
    "Cold Squadron",
    "Catholicism",
    "Democratic Republic of Yrborgh",
    "Tomb of Giants",
    "Circle of the Horn",
    "Swampfolk",
    "Brotherhood of Architects"
  ]
};

function shuffle (array) {
  let result = array.slice();
  for (let i = result.length - 1; i > 0; i--) {
    let swapIndex = Math.floor(Math.random() * (i + 1));
    let temp = result[i];
    result[i] = result[swapIndex];
    result[swapIndex] = temp;
  }

  return result;
}


function generator (key) {
  let list = lists[key];
  let remaining = JSON.parse(window.localStorage.getItem(key)) || [];
  return () => {
    if (remaining.length === 0) {
      remaining = shuffle(list);
    }
    let result = remaining.pop();
    window.localStorage.setItem(key, JSON.stringify(remaining));
    return result;
  };
}

export const name = generator("names");
export const job = generator("jobs");
export const stat = generator("stats");
export const bonus = generator("bonuses");
export const item = generator("items");
export const spell = generator("spells");
export const status = generator("statuses");
export const affiliation = generator("affiliations");
